// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAEdNx8SWiTrgBEfsd6g1gv1oFASiNe64',
    appId: '1:302685663477:web:0c466997bfb6f4e9d9d5bc',
    messagingSenderId: '302685663477',
    projectId: 'carrentalapp-8aec8',
    authDomain: 'carrentalapp-8aec8.firebaseapp.com',
    storageBucket: 'carrentalapp-8aec8.firebasestorage.app',
    measurementId: 'G-NNFS5Y37WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7CasT31I8B9alo77ejSaxVG7ju-kVUu0',
    appId: '1:302685663477:android:b95f9a3ba7074728d9d5bc',
    messagingSenderId: '302685663477',
    projectId: 'carrentalapp-8aec8',
    storageBucket: 'carrentalapp-8aec8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH5G_NnePfbFuWx1PaXNc4oz5Ux-dUk_0',
    appId: '1:302685663477:ios:68083476d91ed023d9d5bc',
    messagingSenderId: '302685663477',
    projectId: 'carrentalapp-8aec8',
    storageBucket: 'carrentalapp-8aec8.firebasestorage.app',
    iosBundleId: 'com.example.carrentalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH5G_NnePfbFuWx1PaXNc4oz5Ux-dUk_0',
    appId: '1:302685663477:ios:68083476d91ed023d9d5bc',
    messagingSenderId: '302685663477',
    projectId: 'carrentalapp-8aec8',
    storageBucket: 'carrentalapp-8aec8.firebasestorage.app',
    iosBundleId: 'com.example.carrentalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAEdNx8SWiTrgBEfsd6g1gv1oFASiNe64',
    appId: '1:302685663477:web:909fba1e39981690d9d5bc',
    messagingSenderId: '302685663477',
    projectId: 'carrentalapp-8aec8',
    authDomain: 'carrentalapp-8aec8.firebaseapp.com',
    storageBucket: 'carrentalapp-8aec8.firebasestorage.app',
    measurementId: 'G-N07K6S5FG9',
  );
}
